---
title: "eTable 8. Joinpoint results by ICD-10 opioid type for the black population, 1999-2015"
output: word_document
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
## Import libraries and make helper functions
library(tidyverse)
num_decimals <- config::get()$num_decimals_supp

import_jp_file <- function(filename) {
    df <- readr::read_delim(filename, delim = ";", escape_double =  FALSE, 
                            trim_ws = TRUE)
    names(df) <- tolower(names(df))
    names(df) <- gsub(" ", "", names(df))
    names(df) <- gsub(",|=|\\.", "_", names(df))
    names(df) <- gsub("-|%|\\(|\\)|\\#", "", names(df))
    
    return(df)
}

import_aapc_file <- function(filename) {
    df <- import_jp_file(filename)
    df <- df %>% 
        mutate(
            period = c(sprintf("%i-%i", startobs, endobs)), 
            aapc = sprintf(paste0("%0.", num_decimals, 
                                  "f (%0.", num_decimals, 
                                  "f, %0.", num_decimals, "f)"), 
                           round(aapc, num_decimals), 
                           round(aapcc_i_low, 2), 
                           round(aapcc_i_high, num_decimals)), 
            pvalue = case_when(
                pvalue < .001 ~ "< 0.001",
                pvalue < .01 ~ "< .01", 
                pvalue < .05 ~ "< .05", 
                TRUE ~ sprintf("= %0.2f", pvalue))) %>% 
        select(-joinpointmodel, -aapcindex, -statisticallysignificant0_no1_yes, 
               -teststatistic, -aapcc_i_low, -aapcc_i_high, -startobs, -endobs)
    
    return(df)
}
```


```{r message=FALSE, warning=FALSE, include=FALSE}
## Import data
## 
## Import the joinpoint AAPC results
icd10_aapc <- import_aapc_file(paste0("./joinpoint_analysis/", 
                                      "04_opioid_rates_icd10type/", 
                                      "04_opioid_rates_icd10type", 
                                      ".aapc.txt")) 

icd10_aapc <- icd10_aapc %>% 
    filter(opioid_type %in% c("heroin", "methadone", "natural", 
                              "synth", "other_op"), 
           race != "total") %>% 
    mutate(opioid_type = factor(opioid_type, 
                                levels = c("heroin", "methadone", 
                                           "natural", "synth", "other_op"), 
                                labels = c("Heroin", "Methadone", "Natural", 
                                           "Synthetic", "Other"), 
                                ordered = TRUE), 
           race = factor(race, 
                         levels = c("white", "black"), 
                         labels = c("White", "Black"), 
                         ordered = TRUE)) %>% 
    select(Race = race, Outcome = opioid_type, `Time period` = period, 
           `Average APC (95% CI)` = aapc, `*P* value` = pvalue)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
## Import APC results
icd10_apc <- import_jp_file(paste0("./joinpoint_analysis/", 
                                   "04_opioid_rates_icd10type/", 
                                   "04_opioid_rates_icd10type", 
                                   ".apc.txt"))

icd10_apc <- icd10_apc  %>% 
    filter(opioid_type %in% c("heroin", "methadone", "natural", 
                              "synth", "other_op"), 
           race != "total") %>% 
    mutate(opioid_type = factor(opioid_type, 
                                levels = c("heroin", "methadone", 
                                           "natural", "synth", "other_op"), 
                                labels = c("Heroin", "Methadone", "Natural", 
                                           "Synthetic", "Other"), 
                                ordered = TRUE), 
           race = factor(race, 
                         levels = c("white", "black"), 
                         labels = c("White", "Black"), 
                         ordered = TRUE)) %>% 
    mutate(segment = sprintf("%i-%i", segmentstart, segmentend), 
           apc = sprintf("%0.2f (%0.2f, %0.2f)", round(apc, 2), 
                         round(apc95lcl, 2), round(apc95ucl, 2)), 
           pvalue = case_when(
               pvalue < .001 ~ "< 0.001",
               pvalue < .01 ~ "< .01", 
               pvalue < .05 ~ "< .05", 
               TRUE ~ sprintf("= %0.2f", pvalue))) %>% 
    select(-segmentstart, -segmentend, -apc95lcl, -apc95ucl, 
           -apcsignificant, -teststatistic) %>% 
    select(Race = race, Outcome = opioid_type, `Time period` = segment, 
           `APC (95% CI)` = apc, `*P* value` = pvalue)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
## Import model estimates
both_df <- import_jp_file(paste0("./joinpoint_analysis/", 
                                 "04_opioid_rates_icd10type/", 
                                 "04_opioid_rates_icd10type", 
                                 ".modelestimates.txt")) 

both_df <- both_df %>% 
    filter(opioid_type %in% c("heroin", "methadone", "natural", 
                              "synth", "other_op"), 
           race != "total") %>% 
    mutate(opioid_type = factor(opioid_type, 
                                levels = c("heroin", "methadone", 
                                           "natural", "synth", "other_op"), 
                                labels = c("Heroin", "Methadone", "Natural", 
                                           "Synthetic", "Other"), 
                                ordered = TRUE), 
           race = factor(race, 
                         levels = c("white", "black"), 
                         labels = c("White", "Black"), 
                         ordered = TRUE)) %>% 
    mutate(interceptpvalue = case_when(
        interceptpvalue < .001 ~ "< 0.001",
        interceptpvalue < .01 ~ "< .01", 
        interceptpvalue < .05 ~ "< .05", 
        TRUE ~ sprintf("= %0.2f", interceptpvalue)), 
        slopepvalue = case_when(
            slopepvalue < .001 ~ "< 0.001",
            slopepvalue < .01 ~ "< .01", 
            slopepvalue < .05 ~ "< .05", 
            TRUE ~ sprintf("= %0.2f", slopepvalue)), 
        slopechgpvalue = case_when(
            slopechgpvalue < .001 ~ "< 0.001",
            slopechgpvalue < .01 ~ "< .01", 
            slopechgpvalue < .05 ~ "< .05", 
            is.na(slopechgpvalue) ~ "NA", 
            TRUE ~ sprintf("= %0.2f", slopechgpvalue)))

model_summaries <- both_df %>% 
    select(opioid_type, race, obs, param, df, sse, mse) %>% 
    distinct() %>% 
    select(Outcome = opioid_type, Race = race, `Obs. (N)` = obs, 
           `Parameters` = param, `Degrees of Freedom` = df, 
           `Sum of squared errors` = sse, `Mean squared error` = mse)

model_estimates <- both_df %>% 
    select(Outcome = opioid_type, race, 
           joinpoint, joinpoint95lcl, joinpoint95ucl, 
           interceptestimate, interceptstderror, interceptpvalue, 
           slopeestimate, slopestderror, slopepvalue, 
           slopechgestimate, slopechgstderror, slopechgpvalue) %>% 
    mutate(
        starting_year = case_when(
            is.na(joinpoint) ~ "1999 (Starting year)", 
            TRUE ~ sprintf("%s (%s, %s)", joinpoint, 
                           joinpoint95lcl, joinpoint95ucl)), 
        intercept = sprintf("%0.2f (%0.2f)", 
                            interceptestimate, interceptstderror), 
        slope =  sprintf(paste0("%0.", num_decimals, 
                                "f (%0.", num_decimals, "f)"), 
                         slopeestimate, slopestderror), 
        slopechg =  case_when(
            is.na(joinpoint) ~ "NA", 
            TRUE ~ sprintf(paste0("%0.", num_decimals, 
                                  "f (%0.", num_decimals, "f)"), 
                           slopechgestimate, 
                           slopechgstderror))) %>% 
    select(Outcome, `Year (95% CI)` = starting_year, 
           `Intercept (SE)`= intercept, 
           `Intercept *P* Value` = interceptpvalue, 
           `Slope (SE)` = slope, `Slope *P* Value` = slopepvalue, 
           `Change in Slope (SE)` = slopechg, 
           `Slope Change *P* Value` = slopechgpvalue, race)
```

# Black population by ICD0-10 type, 1999-2015
## Average APC
```{r echo=FALSE, message=FALSE}
knitr::kable(filter(icd10_aapc, Race == "Black"))
```

## Joinpoint Summary
```{r echo=FALSE, message=FALSE}
knitr::kable(filter(icd10_apc, Race == "Black"))
```

## Joinpoint Model Estimates
### Estimates
```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(model_estimates %>% 
                 filter(race == "Black") %>% 
                 select(-race), 
             digits = num_decimals) 
```

### Summary
```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(model_summaries %>% 
                 filter(Race == "Black") %>% 
                 select(-Race), 
             digits = num_decimals)
```
